sonar.projectKey=LBHackney-IT_lbh-housing-register-search-listener
sonar.organization=lbhackney-it
sonar.sources=HousingRegisterSearchListener
sonar.tests=HousingRegisterSearchListener.Tests
sonar.test.inclusions=HousingRegisterSearchListener.Tests/**
sonar.exclusions=HousingRegisterSearchListener.Tests/**
sonar.dotnet.excludeTestProjects=true
sonar.cs.opencover.reportsPaths="**/coverage.opencover.xml"
